# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_GRI8OltaXdJ0W1PzBZM3-oGpfhNrFKF
"""

# CODE 1: TRAIN (shows epochs/loss/progress)

!pip -q install -U transformers accelerate bitsandbytes peft datasets pandas==2.2.2 openpyxl ipywidgets

import pandas as pd
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer, AutoModelForCausalLM,
    BitsAndBytesConfig, DataCollatorForLanguageModeling,
    TrainingArguments, Trainer
)
from peft import LoraConfig, get_peft_model

# ---- Load file ----
PATH = "/content/قالب_الموشحات_الاندلسية.xlsx"
df = pd.read_excel(PATH)
df.columns = df.columns.astype(str).str.strip()

# ---- Columns (your sheet) ----
POET_COL  = "الشاعر"
TITLE_COL = "عنوان الموشح"
TEXT_COL  = "نص الموشح"
CLS_COL   = "التصنيف"

W1, M1 = "كلمة صعبة 1", "معناها"
W2, M2 = "كلمة صعبة 2", "معناها.1"
W3, M3 = "كلمة صعبة 3", "معناها.2"
W4, M4 = "كلمة صعبة 4", "معناها.3"
W5, M5 = "كلمة صعبة 5", "معناها.4"

INTRO_COL = "تمهيد ثقافي"
EXPL_COL  = "شرح مبسط"

def clean_str(x):
    if pd.isna(x):
        return ""
    return str(x).strip()

def words_block(row):
    pairs = [
        (clean_str(row.get(W1,"")), clean_str(row.get(M1,""))),
        (clean_str(row.get(W2,"")), clean_str(row.get(M2,""))),
        (clean_str(row.get(W3,"")), clean_str(row.get(M3,""))),
        (clean_str(row.get(W4,"")), clean_str(row.get(M4,""))),
        (clean_str(row.get(W5,"")), clean_str(row.get(M5,""))),
    ]
    lines = []
    for i,(w,m) in enumerate(pairs, start=1):
        if w:
            lines.append(f"{i}) {w} — {m if m else 'بدون معنى'}")
    return "\n".join(lines) if lines else "لا توجد كلمات صعبة مسجلة"

#  تدريب فقط على الصفوف المكتملة (تمهيد + شرح) + عندها نص موشح
train_df = df[
    (df[TEXT_COL].notna()) & (df[TEXT_COL].astype(str).str.strip() != "") &
    (df[INTRO_COL].notna()) & (df[EXPL_COL].notna()) &
    (df[INTRO_COL].astype(str).str.strip() != "") &
    (df[EXPL_COL].astype(str).str.strip() != "")
].copy()

def build_train_text(row):
    poet  = clean_str(row.get(POET_COL,"")) or "غير مذكور"
    title = clean_str(row.get(TITLE_COL,"")) or "غير مذكور"
    cls   = clean_str(row.get(CLS_COL,"")) or "غير محدد"
    text  = clean_str(row.get(TEXT_COL,""))
    wb    = words_block(row)

    intro = clean_str(row.get(INTRO_COL,""))
    expl  = clean_str(row.get(EXPL_COL,""))

    prompt = f"""أنت مساعد أدبي متخصص في الموشحات الأندلسية.
المطلوب: اكتب (1) تمهيد ثقافي ثم (2) شرح مبسط للموشح.
استفد من الكلمات الصعبة ومعانيها داخل الشرح إن أمكن.

المعلومات:
- الشاعر: {poet}
- العنوان: {title}
- التصنيف: {cls}

نص الموشح:
{text}

الكلمات الصعبة ومعانيها:
{wb}

التزم بالتنسيق:
✨ التمهيد الثقافي:
...

💡 الشرح المبسط:
...
"""

    answer = f"""✨ التمهيد الثقافي:
{intro}

💡 الشرح المبسط:
{expl}
"""
    return prompt + "\n" + answer

texts = train_df.apply(build_train_text, axis=1).tolist()
ds = Dataset.from_dict({"text": texts})
split = ds.train_test_split(test_size=0.05, seed=42)
train_ds, eval_ds = split["train"], split["test"]

# ---- Load model (QLoRA 4-bit) ----
MODEL_NAME = "Qwen/Qwen2.5-3B-Instruct"

bnb = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

tok = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
if tok.pad_token is None:
    tok.pad_token = tok.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb,
    device_map="auto"
)

# ---- LoRA ----
lora = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj","k_proj","v_proj","o_proj"]
)
model = get_peft_model(base_model, lora)

# ---- Tokenize ----
MAX_LEN = 1024
def tokenize_fn(batch):
    enc = tok(batch["text"], truncation=True, max_length=MAX_LEN, padding="max_length")
    enc["labels"] = enc["input_ids"].copy()
    return enc

train_tok = train_ds.map(tokenize_fn, batched=True, remove_columns=["text"])
eval_tok  = eval_ds.map(tokenize_fn, batched=True, remove_columns=["text"])

collator = DataCollatorForLanguageModeling(tokenizer=tok, mlm=False)

# Train (Epoch/Loss/Progress will show automatically)
args = TrainingArguments(
    output_dir="/content/muwashah_qlora_out",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    num_train_epochs=8,
    learning_rate=2e-4,
    logging_steps=5,
    save_steps=25,
    fp16=True,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_tok,
    eval_dataset=eval_tok,
    data_collator=collator
)

trainer.train()
print("Training done")

# CODE 2

import os, re, pandas as pd, torch
import ipywidgets as widgets
from IPython.display import display, clear_output

#  hide transformers warnings
os.environ["TRANSFORMERS_VERBOSITY"] = "error"
os.environ["BITSANDBYTES_NOWELCOME"] = "1"
try:
    from transformers.utils import logging as hf_logging
    hf_logging.set_verbosity_error()
except Exception:
    pass

# ---- Ensure df exists ----
try:
    df
except NameError:
    PATH = "/content/قالب_الموشحات_الاندلسية (1).xlsx"
    df = pd.read_excel(PATH)
    df.columns = df.columns.astype(str).str.strip()

# ---- Ensure model & tok exist ----
try:
    model; tok
except NameError:
    print("❌ لازم تشغّلين كود التدريب (CODE 1) في نفس الجلسة.")
    raise SystemExit

# ---- Columns ----
POET_COL  = "الشاعر"
TITLE_COL = "عنوان الموشح"
TEXT_COL  = "نص الموشح"
CLS_COL   = "التصنيف"

W1, M1 = "كلمة صعبة 1", "معناها"
W2, M2 = "كلمة صعبة 2", "معناها.1"
W3, M3 = "كلمة صعبة 3", "معناها.2"
W4, M4 = "كلمة صعبة 4", "معناها.3"
W5, M5 = "كلمة صعبة 5", "معناها.4"

# ---- Helpers ----
def clean(x):
    if pd.isna(x): return ""
    return str(x).strip()

def normalize_ar(s: str) -> str:
    s = "" if pd.isna(s) else str(s)
    s = s.strip()
    s = re.sub(r"[\u200f\u200e\u202a-\u202e\u2066-\u2069]", "", s)
    s = s.replace("ـ","")
    s = re.sub(r"\s+"," ",s).strip()
    return s

def words_block(row):
    pairs = [
        (clean(row.get(W1,"")), clean(row.get(M1,""))),
        (clean(row.get(W2,"")), clean(row.get(M2,""))),
        (clean(row.get(W3,"")), clean(row.get(M3,""))),
        (clean(row.get(W4,"")), clean(row.get(M4,""))),
        (clean(row.get(W5,"")), clean(row.get(M5,""))),
    ]
    lines=[]
    idx=1
    for w,m in pairs:
        if w:
            lines.append(f"{idx}) {w} — {m if m else 'بدون معنى'}")
            idx += 1
    return "\n".join(lines) if lines else "لا توجد كلمات صعبة مسجلة"

# ---- Arabic cleanup ----
ARABIC_ONLY = re.compile(
    r"[^\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF0-9\s\.\,\!\?\:\;\-\–\—\(\)\[\]\{\}«»\"\'\nـ]"
)
AR_LET = re.compile(r"[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF]")

def fix_arabic_spacing(text: str) -> str:
    if not text: return ""
    text = re.sub(r"[\u200f\u200e\u202a-\u202e\u2066-\u2069]", " ", text)
    text = re.sub(r"[ \t]+", " ", text).strip()
    text = re.sub(r"\bال\s+([اأإآء-ي])", r"ال\1", text)
    text = re.sub(r"\b([وفبكلس])\s+([اأإآء-ي])", r"\1\2", text)
    text = re.sub(r"\bالم\s+([اأإآء-ي])", r"الم\1", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

COMMON_FIXES = [
    (r"\bتمهد\b", "تمهيد"),
    (r"\bثقالي\b", "ثقافي"),
    (r"\bالم بسط\b", "المبسط"),
    (r"\bالمتو ع(?:ة|ه)\b", "المتنوعة"),
    (r"\bتتمة الثقافة\b", ""),
    (r"\bالشرح\s*:\b", ""),
]

def clean_arabic_output(text: str) -> str:
    text = (text or "").strip()
    text = ARABIC_ONLY.sub("", text)
    text = fix_arabic_spacing(text)
    for pat, rep in COMMON_FIXES:
        text = re.sub(pat, rep, text)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    text = re.sub(r"\s+", " ", text).strip()
    return text

# ---- Robust header extraction (works even if no ✨💡 and even if in one line) ----
INTRO_TAG = "✨ التمهيد الثقافي:"
EXPL_TAG  = "💡 الشرح المبسط:"

def standardize_tags(t: str) -> str:
    t = (t or "").strip()

    # unify different header spellings into standard tags
    t = re.sub(r"(✨\s*)?التمهيد\s*الثقافي\s*[:：\-]?", INTRO_TAG, t)
    t = re.sub(r"(💡\s*)?الشرح\s*المبسط\s*[:：\-]?", EXPL_TAG, t)

    # also handle "تمهيد ثقافي" without "ال"
    t = re.sub(r"(✨\s*)?تمهيد\s*ثقافي\s*[:：\-]?", INTRO_TAG, t)
    t = re.sub(r"(💡\s*)?شرح\s*مبسط\s*[:：\-]?", EXPL_TAG, t)

    return t

def extract_first_intro_expl(raw: str):
    t = clean_arabic_output(raw)
    t = standardize_tags(t)

    # ensure tags exist
    if INTRO_TAG not in t or EXPL_TAG not in t:
        # fallback: split into 2 chunks
        parts = re.split(r"\.|\!|\؟|\?", t)
        parts = [p.strip() for p in parts if p.strip()]
        intro = " ".join(parts[:2]).strip()
        expl  = " ".join(parts[2:6]).strip()
        return intro, expl

    # take from first intro to first expl after it
    t = t[t.find(INTRO_TAG):].strip()
    before, after = t.split(EXPL_TAG, 1)
    intro = before.replace(INTRO_TAG, "").strip()

    # cut explanation at any repeated tag
    stop_positions = []
    for m in [INTRO_TAG, EXPL_TAG]:
        j = after.find(m)
        if j != -1:
            stop_positions.append(j)
    expl = after[:min(stop_positions)] if stop_positions else after
    expl = expl.strip()

    return intro, expl

def strip_inner_labels(s: str) -> str:
    # remove repeated labels inside content
    s = re.sub(r"(✨\s*)?التمهيد\s*الثقافي\s*[:：\-]?", "", s)
    s = re.sub(r"(💡\s*)?الشرح\s*المبسط\s*[:：\-]?", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def scrub_forbidden(s: str, poet: str, title: str, cls: str) -> str:
    # remove accidental mentions of poet/title/class inside generated text
    for v in [poet, title, cls]:
        v = (v or "").strip()
        if v:
            s = s.replace(v, "")
    s = re.sub(r"\s+", " ", s).strip()
    return s

def format_final(intro: str, expl: str, poet: str, title: str, cls: str) -> str:
    intro = clean_arabic_output(intro)
    expl  = clean_arabic_output(expl)

    intro = strip_inner_labels(intro)
    expl  = strip_inner_labels(expl)

    intro = scrub_forbidden(intro, poet, title, cls)
    expl  = scrub_forbidden(expl, poet, title, cls)

    return f"{INTRO_TAG}\n{intro}\n\n{EXPL_TAG}\n{expl}".strip()

def looks_ok(final_text: str) -> bool:
    if not final_text: return False
    if INTRO_TAG not in final_text or EXPL_TAG not in final_text: return False
    if not AR_LET.search(final_text): return False
    if len(final_text) < 120: return False
    if re.search(r"[A-Za-z\u4e00-\u9fff]", final_text): return False
    return True

# ---- Allowed rows ----
allowed = df[
    (df[POET_COL].notna())  & (df[POET_COL].astype(str).str.strip()!="") &
    (df[TITLE_COL].notna()) & (df[TITLE_COL].astype(str).str.strip()!="") &
    (df[TEXT_COL].notna())  & (df[TEXT_COL].astype(str).str.strip()!="")
].copy()

allowed["_poet_norm"]  = allowed[POET_COL].apply(normalize_ar)
allowed["_title_norm"] = allowed[TITLE_COL].apply(normalize_ar)

# ---- UI ----
poets = sorted(allowed["_poet_norm"].unique().tolist())
poet_dd  = widgets.Dropdown(options=poets, description="الشاعر:", style={"description_width":"initial"})
title_dd = widgets.Dropdown(options=[], description="الموشح:", style={"description_width":"initial"})
btn = widgets.Button(description="إخراج", button_style="success")
out = widgets.Output()

def update_titles(*args):
    p = poet_dd.value
    titles = (
        allowed.loc[allowed["_poet_norm"]==p, "_title_norm"]
        .dropna().astype(str).unique().tolist()
    )
    title_dd.options = sorted(titles)

poet_dd.observe(update_titles, names="value")
update_titles()

# ---- Generator ----
def generate_intro_expl(row, max_new_tokens=260, retries=6):
    model.eval()

    poet  = normalize_ar(row.get(POET_COL))
    title = normalize_ar(row.get(TITLE_COL))
    cls   = normalize_ar(row.get(CLS_COL))
    text_full = clean(row.get(TEXT_COL))
    wb = words_block(row)

    text_for_prompt = text_full[:1200]

    system_msg = (
        "أنت كاتب أدبي عربي متخصص في الموشحات الأندلسية. "
        "اكتب بالعربية الفصحى السليمة فقط. "
        "ممنوع أي لغة أجنبية أو أحرف غير عربية. "
        "ممنوع تكرار العناوين أو تكرار الفقرات. "
        "لا تخترع أسماء أو معلومات غير موجودة. "
        "اكتب فقط قسمين: تمهيد ثقافي ثم شرح مبسط."
    )

    user_msg = f"""اكتب فقط النص التالي وبنفس الصيغة حرفيًا (سطرين عناوين + فقرتين):

✨ التمهيد الثقافي:
(فقرة واحدة 3-5 جمل)

💡 الشرح المبسط:
(فقرة واحدة 5-7 جمل)

شروط صارمة:
- لا تكرر أي عنوان أو فقرة.
- لا تكتب "التمهيد الثقافي:" داخل الفقرة.
- لا تكتب "الشرح المبسط:" داخل الفقرة.
- لا تذكر الشاعر/العنوان/التصنيف داخل الفقرتين.
- لا تقتبس أبياتًا.
- توقف بعد الشرح مباشرة.

للاطلاع فقط:
نص الموشح:
{text_for_prompt}

الكلمات الصعبة ومعانيها:
{wb}
"""

    messages = [
        {"role":"system","content":system_msg},
        {"role":"user","content":user_msg},
    ]

    prompt = tok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tok(prompt, return_tensors="pt").to(model.device)

    last_final = ""
    for _ in range(retries):
        with torch.no_grad():
            out_ids = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                do_sample=False,
                repetition_penalty=1.22,
                eos_token_id=tok.eos_token_id,
                pad_token_id=tok.eos_token_id
            )

        new_tokens = out_ids[0][inputs["input_ids"].shape[-1]:]
        gen = tok.decode(new_tokens, skip_special_tokens=True)

        intro, expl = extract_first_intro_expl(gen)
        final = format_final(intro, expl, poet, title, cls)
        last_final = final

        if looks_ok(final):
            return final

    return last_final if last_final else "❌ ما طلع نص."

# ---- Button action ----
def on_click(_):
    with out:
        clear_output(wait=True)

        row = allowed[
            (allowed["_poet_norm"]==poet_dd.value) &
            (allowed["_title_norm"]==title_dd.value)
        ].iloc[0]

        poet  = normalize_ar(row.get(POET_COL))
        title = normalize_ar(row.get(TITLE_COL))
        cls   = normalize_ar(row.get(CLS_COL))
        text  = clean(row.get(TEXT_COL))
        wb    = words_block(row)

        print("="*95)
        print(f"الشاعر   : {poet}")
        print(f"العنوان  : {title}")
        print(f"التصنيف  : {cls}")
        print("-"*95)
        print("نص الموشح:\n")
        print(text)
        print("-"*95)
        print("الكلمات الصعبة ومعانيها :\n")
        print(wb)
        print("="*95)

        result = generate_intro_expl(row)
        print("\n" + result)

btn.on_click(on_click)
display(widgets.VBox([poet_dd, title_dd, btn, out]))